Add align attribute to divider
mjmlio/mjml pull request #2087
Opened 2020-11-11 22:02 UTC by thierrylemoulec

Hi! I'd like to add align attribute for `<mj-divider />`, so I created this pull request.

I can't include litmus/email on acid screenshot because I don't have an account. But if there is a compatibility issue I'd be happy to work on it and provide a working version for this simple feature.

This PR would help resolve this issue #407 without using a workaround.

2020-11-23 10:28 UTC, iRyusa commented
This need to be tested first cc @kmcb777

2020-12-22 16:54 UTC, kmcb777 requested changes

2020-12-22 16:54 UTC, kmcb777 commented on packages/mjml-divider/src/index.js
> +    align: 'enum(left, center, right)',
Here there must be no spaces before 'center' and 'right', otherwise the validator expects those spaces

2020-12-22 16:57 UTC, kmcb777 commented
Hi @thierrylemoulec thanks for this PR !
Could you remove the spaces in the allowedAttributes, cf. my previous comment
One more thing is needed for this to work in outlook :
In `renderAfter` on line 84, `align: 'center'` needs to be replaced with `align: this.getAttribute('align'),`
With this fix it seems to work perfectly everywhere 👍

2020-12-28 16:24 UTC, kmcb777 commented
i'd like to include this in tomorrow's release so i'll merge this and add the little fix

2020-12-28 16:24 UTC, merged

2021-01-04 15:14 UTC, thierrylemoulec commented
@kmcb777 Sorry for the delayed response. I wasn't available. Thanks for doing the fix and merging the feature. 👍